In [1]:
import numpy as np
import sklearn
import pickle

In [2]:
from sklearn.mixture import GaussianMixture

In [3]:
gmm = GaussianMixture(n_components=7)

In [4]:
X = []
y = []
with open("layers300ish.txt") as f:
    newlines = f.readlines()
    for x in newlines:
        if x == "\n":
            continue
        
        real_thing = x.split("]")
        
        hehe = real_thing[0].split(" ")
        emotion = hehe[len(hehe) - 1]
        arr = (real_thing[0].replace(emotion, "") + "]").replace("[", "").replace("]", "")
        new_arr = np.array(arr.split(","))
        
        final_arr = []
        for temp_str in new_arr:
            if (temp_str != " "):
                final_arr.append(float(temp_str.replace(",", "")))
        
        X.append(final_arr)
        y.append(emotion)

def save_model(file_name, model):
    pkl_filename = file_name  
    with open(file_name, 'wb') as file:  
        pickle.dump(model, file)
        
def get_model(file_name):
    with open(file_name, 'rb') as file:
        temp_model = pickle.load(file)
        return temp_model

In [5]:
len(X)

368

In [6]:
len(y)

368

In [7]:
y[0]

'joy'

In [8]:
len(X[1])

85

In [9]:
y[0]

'joy'

In [47]:
from sklearn.preprocessing import OneHotEncoder

In [48]:
enc = OneHotEncoder()

In [50]:
temp_y = np.array(y)
enc.fit(temp_y.reshape(-1, 1))

OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

In [54]:
enc.categories

# GMM WITHOUT TRAINING

In [10]:
gmm.fit(X)

GaussianMixture(covariance_type='full', init_params='kmeans', max_iter=100,
        means_init=None, n_components=7, n_init=1, precisions_init=None,
        random_state=None, reg_covar=1e-06, tol=0.001, verbose=0,
        verbose_interval=10, warm_start=False, weights_init=None)

In [11]:
gmm.sample(1)

(array([[ 1.47327508e-02,  2.06807519e-01,  8.61460681e-03,
          4.10351038e-03,  7.59248608e-03,  9.91733438e-03,
          3.20142272e-03,  1.61841524e-03,  4.57520432e-03,
          3.79827628e-03,  3.58160232e-03,  1.58019349e-03,
          1.49100264e-03,  9.73445416e-03,  6.89552900e-03,
         -4.14564018e-03,  1.06351374e-02,  1.74231780e-02,
          2.08573305e-03,  7.05702204e-03,  3.17665026e-03,
          3.24551543e-03,  4.55217048e-03,  3.60715964e-03,
          4.06522692e-03,  1.75709985e-03,  5.68614313e-03,
          3.48527671e-03,  9.36954523e-03,  4.46322682e-03,
          5.70572061e-03,  3.84882258e-03,  3.64628868e-03,
          2.44892346e-03, -9.32416738e-04,  5.28807550e-03,
          7.47197838e-03,  4.89170893e-03,  3.58268426e-03,
          1.30224914e-03,  3.65425538e-03,  1.28198083e-03,
          5.88418940e-03,  4.63122480e-03,  2.06901047e-03,
          3.90443614e-03,  1.03210833e-02,  8.12745691e-03,
          7.29804957e-03,  7.02913664e-0

In [25]:
n_components = len(gmm.weights_)
n_components

7

In [26]:
emotions = gmm.sample(5)[0]
emotions

array([[ 8.67883077e-03,  7.55383272e-02,  1.14243987e-02,
         8.12443796e-03,  8.49548745e-03,  1.02339729e-02,
         1.02073058e-02,  1.93401754e-02,  9.73208719e-03,
         9.86605825e-03,  6.30505840e-03,  1.71375738e-02,
         5.50185777e-03,  1.42692017e-02,  1.15684660e-02,
         7.66902852e-03,  7.81993404e-03,  4.28790551e-03,
         1.42814274e-02,  9.63887440e-03,  6.68701311e-03,
         1.06822575e-02,  8.08369047e-03,  1.51348491e-02,
         1.07478701e-02,  1.08971300e-02,  1.10766351e-02,
         4.76620971e-03,  6.85799522e-03,  1.37064483e-02,
         9.77373206e-03,  1.11123208e-02,  1.13613576e-02,
         7.03851534e-03,  1.05907043e-02,  1.50637250e-02,
         1.02464239e-02,  1.13931656e-02,  1.03064232e-02,
         1.41975658e-02,  6.35193512e-03,  8.51900163e-03,
         8.91250287e-03,  1.17899802e-02,  1.05536050e-02,
         1.04151177e-02,  2.14271292e-03,  1.16976008e-02,
         1.27716862e-02,  7.74171043e-03,  1.76709175e-0

# GMM with training

# testing loading in

In [27]:
save_model("unsupervised_7_emotions.pkl", gmm)

In [28]:
model = get_model("unsupervised_7_emotions.pkl")

In [29]:
model.sample()

(array([[ 1.76079413e-03,  3.87681571e-01,  1.19519017e-03,
          3.61196446e-03,  5.31375975e-03,  6.85196746e-04,
         -1.34808372e-03,  4.01479479e-03,  3.23755821e-03,
          1.61544363e-03,  1.84507585e-03,  2.44906266e-03,
          4.61400160e-03,  5.77113874e-03,  1.22365200e-03,
          2.41560898e-03,  2.90792090e-03, -9.42056777e-05,
          4.75857748e-03,  2.90813361e-03,  3.84082043e-03,
          3.84759858e-03,  3.06182110e-03,  7.28724320e-03,
          6.08491693e-03,  2.71271846e-03,  7.08442637e-05,
          3.23798799e-03,  5.59445786e-03, -1.89256195e-03,
          3.37283556e-03,  2.36486590e-03,  3.76203591e-03,
         -2.66343113e-04,  2.81306708e-03,  5.24208705e-03,
          3.78605729e-03,  6.30359369e-03,  2.96946214e-03,
          2.76056439e-03,  3.46482636e-03,  5.65965476e-04,
          1.56005465e-03,  4.83182568e-03,  3.01288672e-03,
          4.97336885e-04, -1.18638603e-03,  4.91212407e-03,
          6.87565239e-04,  3.93901674e-0