In [16]:
import numpy as np
import sklearn
import pickle

In [17]:
from sklearn.mixture import GaussianMixture

In [18]:
gmm = GaussianMixture(n_components=7)

In [20]:
X = []
y = []
with open("../embeddings/word_vec_tfidf.txt") as f:
    newlines = f.readlines()
    for x in newlines:
        if x == "\n":
            continue
        
        real_thing = x.split("]")
        
        hehe = real_thing[0].split(" ")
        emotion = hehe[len(hehe) - 1]
        arr = (real_thing[0].replace(emotion, "") + "]").replace("[", "").replace("]", "")
        new_arr = np.array(arr.split(","))
        
        final_arr = []
        for temp_str in new_arr:
            if (temp_str != " "):
                final_arr.append(float(temp_str.replace(",", "")))
        
        X.append(final_arr)
        y.append(emotion)

def save_model(file_name, model):
    pkl_filename = file_name  
    with open(file_name, 'wb') as file:  
        pickle.dump(model, file)
        
def get_model(file_name):
    with open(file_name, 'rb') as file:
        temp_model = pickle.load(file)
        return temp_model

In [21]:
len(X)

7666

In [22]:
len(y)

7666

In [23]:
y[0]

'anger'

In [24]:
len(X[1])

384

In [25]:
y[0]

'anger'

In [47]:
from sklearn.preprocessing import OneHotEncoder

In [48]:
enc = OneHotEncoder()

In [50]:
temp_y = np.array(y)
enc.fit(temp_y.reshape(-1, 1))

OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

In [54]:
enc.categories

# GMM WITHOUT TRAINING

In [26]:
gmm.fit(X)

GaussianMixture(covariance_type='full', init_params='kmeans', max_iter=100,
        means_init=None, n_components=7, n_init=1, precisions_init=None,
        random_state=None, reg_covar=1e-06, tol=0.001, verbose=0,
        verbose_interval=10, warm_start=False, weights_init=None)

In [27]:
gmm.sample(1)

(array([[-1.20039365e-01,  9.97438966e-02, -1.38201554e-01,
          1.15509997e+00, -3.59929518e-01,  7.30561706e-02,
         -6.59373226e-01,  8.47122288e-02,  2.36794749e-01,
          1.45976899e-01,  4.22207698e-01, -4.04958499e-01,
         -6.08972449e-02,  1.86170107e-01, -1.26325561e-01,
          3.40463794e-01, -5.27736397e-01, -5.51226452e-01,
         -1.43599484e-01,  6.26018490e-02,  4.86155776e-01,
          2.15787617e-01, -1.56451827e-01,  3.29073099e-01,
         -5.34175996e-01, -1.82497871e-01, -4.73130515e-01,
          3.99911191e-01, -6.79883932e-01, -2.25939762e-02,
          2.07537917e-01,  6.81255520e-01,  6.60422587e-01,
         -5.08472070e-01,  4.97733203e-03,  2.12079447e-01,
          7.90963447e-01,  1.58401687e-01,  2.18380730e-01,
         -5.52714703e-01, -7.78551171e-01,  3.37521489e-01,
          7.52495137e-01, -6.66031354e-02, -3.85628178e-01,
          3.65149561e-01,  7.31773364e-01, -3.67388545e-01,
          6.78884587e-01, -1.17390932e-0

In [28]:
n_components = len(gmm.weights_)
n_components

7

In [26]:
emotions = gmm.sample(5)[0]
emotions

array([[ 8.67883077e-03,  7.55383272e-02,  1.14243987e-02,
         8.12443796e-03,  8.49548745e-03,  1.02339729e-02,
         1.02073058e-02,  1.93401754e-02,  9.73208719e-03,
         9.86605825e-03,  6.30505840e-03,  1.71375738e-02,
         5.50185777e-03,  1.42692017e-02,  1.15684660e-02,
         7.66902852e-03,  7.81993404e-03,  4.28790551e-03,
         1.42814274e-02,  9.63887440e-03,  6.68701311e-03,
         1.06822575e-02,  8.08369047e-03,  1.51348491e-02,
         1.07478701e-02,  1.08971300e-02,  1.10766351e-02,
         4.76620971e-03,  6.85799522e-03,  1.37064483e-02,
         9.77373206e-03,  1.11123208e-02,  1.13613576e-02,
         7.03851534e-03,  1.05907043e-02,  1.50637250e-02,
         1.02464239e-02,  1.13931656e-02,  1.03064232e-02,
         1.41975658e-02,  6.35193512e-03,  8.51900163e-03,
         8.91250287e-03,  1.17899802e-02,  1.05536050e-02,
         1.04151177e-02,  2.14271292e-03,  1.16976008e-02,
         1.27716862e-02,  7.74171043e-03,  1.76709175e-0

# GMM with training

# testing loading in

In [29]:
save_model("emotions_7_tfidf_wordvec.pkl", gmm)

In [30]:
model = get_model("emotions_7_tfidf_wordvec.pkl")

In [31]:
model.sample()

(array([[ 1.61012544e-01,  2.73218785e-01,  8.16931640e-02,
          2.52706532e-01, -3.33571113e-01,  1.07878588e-01,
         -5.82625266e-01, -2.97491724e-01,  9.97818797e-02,
          2.46478028e-01,  8.50835918e-02, -7.86638599e-02,
          7.80081316e-02, -2.36295031e-01, -1.36535721e-01,
         -3.34183685e-01, -4.14843083e-01, -2.23754071e-01,
         -2.40877411e-01,  7.74705143e-02,  2.25565557e-01,
         -1.09023238e-02,  3.81381801e-01,  4.77129193e-01,
          6.57627714e-02, -1.08042618e-01, -2.34922338e-01,
          1.85069605e-01, -2.11871462e-01, -1.10058215e-01,
         -2.80344994e-01,  2.29947457e-01,  4.37430436e-01,
         -1.29114806e-01, -1.68780930e-01, -2.31776537e-01,
          3.94687208e-01, -7.84163558e-02,  3.44036399e-01,
         -1.49706335e-01, -3.06085020e-01,  1.74644353e-01,
         -9.73484803e-02,  3.45242047e-02, -1.41690007e-01,
         -2.79885022e-02, -3.30233281e-02, -2.18832730e-01,
          6.16567762e-01,  1.56859520e-0